version: "3.8"
services:
  dcs-rabbitmq:
    image: rabbitmq:3-management
    container_name: dcs-rabbitmq
    restart: always
    ports:
      - 5672:5672  # Porta padrão para comunicação do RabbitMQ
      - 15672:15672  # Porta para o console de gerenciamento do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
networks:
  default:
    name: local-network
    external: true
